###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "reps": 12,
    "weight": 50,
    "unit": "lbs",
    "date": "08-06-21"
}

###
GET http://localhost:3000/exercises HTTP/1.1

###
GET http://localhost:3000/exercises/6111af86ffdccf245c3db1c2 HTTP/1.1

###

PUT http://localhost:3000/exercises/6111b91c4c751c63a84b5be5 HTTP/1.1
content-type: application/json

{
    "name": "Goblet Squat",
    "reps": 4,
    "weight": 40,
    "unit": "kgs",
    "date": "08-05-21"
}

###
DELETE http://localhost:3000/exercises/6111b9384c751c63a84b5be9 HTTP/1.1


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Sumo Squat",
    "reps": 6,
    "weight": 20,
    "unit": "kgs",
    "date": "08-06-21"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Goblet Squat",
    "reps": 10,
    "weight": 20,
    "unit": "lbs",
    "date": "08-06-21"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Upright Row",
    "reps": 6,
    "weight": 20,
    "unit": "kgs",
    "date": "08-08-21"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Reverse Lunges",
    "reps": 12,
    "weight": 55,
    "unit": "lbs",
    "date": "08-06-21"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "A Serious Man",
    "year": 2009,
    "language": "English"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "City Of God",
    "year": 2003,
    "language": "Portuguese"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "Parasite",
    "year": 2019,
    "language": "Korean"
}
