###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "reps": 12,
    "weight": 50,
    "unit": "lbs",
    "date": "08-06-21"
}

###
GET http://localhost:3000/exercises HTTP/1.1

###
GET http://localhost:3000/exercises/6111af86ffdccf245c3db1c2 HTTP/1.1

###

PUT http://localhost:3000/exercises/61113eb87094a14718b99347 HTTP/1.1
content-type: application/json

{
    "title": "Sorry to Bother You",
    "year": 2018,
    "language": "English"
}

###
DELETE http://localhost:3000/exercises/61113eb87094a14718b99347 HTTP/1.1


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Sumo Squat",
    "reps": 6,
    "weight": 20,
    "unit": "kgs",
    "date": "08-06-21"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "High Fidelity",
    "year": 2000,
    "language": "English"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "Anchorman",
    "year": 2004,
    "language": "English"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "No Country For Old Men",
    "year": 2007,
    "language": "English"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "A Serious Man",
    "year": 2009,
    "language": "English"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "City Of God",
    "year": 2003,
    "language": "Portuguese"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "Parasite",
    "year": 2019,
    "language": "Korean"
}
